/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutVisualizeRouteRouteImport } from './routes/_layout/visualize/route'
import { Route as LayoutSynchronizeInterrogationRouteRouteImport } from './routes/_layout/synchronize-interrogation/route'
import { Route as LayoutSynchronizeRouteRouteImport } from './routes/_layout/synchronize/route'
import { Route as LayoutReviewInterrogationsRouteRouteImport } from './routes/_layout/review-interrogations/route'
import { Route as LayoutInterrogationsRouteRouteImport } from './routes/_layout/interrogations/route'
import { Route as LayoutExternalRouteRouteImport } from './routes/_layout/external/route'
import { Route as LayoutEnvRouteRouteImport } from './routes/_layout/env/route'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutVisualizeRouteRoute = LayoutVisualizeRouteRouteImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSynchronizeInterrogationRouteRoute =
  LayoutSynchronizeInterrogationRouteRouteImport.update({
    id: '/synchronize-interrogation',
    path: '/synchronize-interrogation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSynchronizeRouteRoute = LayoutSynchronizeRouteRouteImport.update({
  id: '/synchronize',
  path: '/synchronize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewInterrogationsRouteRoute =
  LayoutReviewInterrogationsRouteRouteImport.update({
    id: '/review-interrogations',
    path: '/review-interrogations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInterrogationsRouteRoute =
  LayoutInterrogationsRouteRouteImport.update({
    id: '/interrogations',
    path: '/interrogations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExternalRouteRoute = LayoutExternalRouteRouteImport.update({
  id: '/external',
  path: '/external',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvRouteRoute = LayoutEnvRouteRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteWithChildren
  '/env': typeof LayoutEnvRouteRoute
  '/external': typeof LayoutExternalRouteRoute
  '/interrogations': typeof LayoutInterrogationsRouteRoute
  '/review-interrogations': typeof LayoutReviewInterrogationsRouteRoute
  '/synchronize': typeof LayoutSynchronizeRouteRoute
  '/synchronize-interrogation': typeof LayoutSynchronizeInterrogationRouteRoute
  '/visualize': typeof LayoutVisualizeRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteWithChildren
  '/env': typeof LayoutEnvRouteRoute
  '/external': typeof LayoutExternalRouteRoute
  '/interrogations': typeof LayoutInterrogationsRouteRoute
  '/review-interrogations': typeof LayoutReviewInterrogationsRouteRoute
  '/synchronize': typeof LayoutSynchronizeRouteRoute
  '/synchronize-interrogation': typeof LayoutSynchronizeInterrogationRouteRoute
  '/visualize': typeof LayoutVisualizeRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/env': typeof LayoutEnvRouteRoute
  '/_layout/external': typeof LayoutExternalRouteRoute
  '/_layout/interrogations': typeof LayoutInterrogationsRouteRoute
  '/_layout/review-interrogations': typeof LayoutReviewInterrogationsRouteRoute
  '/_layout/synchronize': typeof LayoutSynchronizeRouteRoute
  '/_layout/synchronize-interrogation': typeof LayoutSynchronizeInterrogationRouteRoute
  '/_layout/visualize': typeof LayoutVisualizeRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/env'
    | '/external'
    | '/interrogations'
    | '/review-interrogations'
    | '/synchronize'
    | '/synchronize-interrogation'
    | '/visualize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/env'
    | '/external'
    | '/interrogations'
    | '/review-interrogations'
    | '/synchronize'
    | '/synchronize-interrogation'
    | '/visualize'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/env'
    | '/_layout/external'
    | '/_layout/interrogations'
    | '/_layout/review-interrogations'
    | '/_layout/synchronize'
    | '/_layout/synchronize-interrogation'
    | '/_layout/visualize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/visualize': {
      id: '/_layout/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof LayoutVisualizeRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/synchronize-interrogation': {
      id: '/_layout/synchronize-interrogation'
      path: '/synchronize-interrogation'
      fullPath: '/synchronize-interrogation'
      preLoaderRoute: typeof LayoutSynchronizeInterrogationRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/synchronize': {
      id: '/_layout/synchronize'
      path: '/synchronize'
      fullPath: '/synchronize'
      preLoaderRoute: typeof LayoutSynchronizeRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review-interrogations': {
      id: '/_layout/review-interrogations'
      path: '/review-interrogations'
      fullPath: '/review-interrogations'
      preLoaderRoute: typeof LayoutReviewInterrogationsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interrogations': {
      id: '/_layout/interrogations'
      path: '/interrogations'
      fullPath: '/interrogations'
      preLoaderRoute: typeof LayoutInterrogationsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external': {
      id: '/_layout/external'
      path: '/external'
      fullPath: '/external'
      preLoaderRoute: typeof LayoutExternalRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env': {
      id: '/_layout/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof LayoutEnvRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutEnvRouteRoute: typeof LayoutEnvRouteRoute
  LayoutExternalRouteRoute: typeof LayoutExternalRouteRoute
  LayoutInterrogationsRouteRoute: typeof LayoutInterrogationsRouteRoute
  LayoutReviewInterrogationsRouteRoute: typeof LayoutReviewInterrogationsRouteRoute
  LayoutSynchronizeRouteRoute: typeof LayoutSynchronizeRouteRoute
  LayoutSynchronizeInterrogationRouteRoute: typeof LayoutSynchronizeInterrogationRouteRoute
  LayoutVisualizeRouteRoute: typeof LayoutVisualizeRouteRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutEnvRouteRoute: LayoutEnvRouteRoute,
  LayoutExternalRouteRoute: LayoutExternalRouteRoute,
  LayoutInterrogationsRouteRoute: LayoutInterrogationsRouteRoute,
  LayoutReviewInterrogationsRouteRoute: LayoutReviewInterrogationsRouteRoute,
  LayoutSynchronizeRouteRoute: LayoutSynchronizeRouteRoute,
  LayoutSynchronizeInterrogationRouteRoute:
    LayoutSynchronizeInterrogationRouteRoute,
  LayoutVisualizeRouteRoute: LayoutVisualizeRouteRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
