/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutEnvRouteRouteImport } from './routes/_layout/env/route'
import { Route as LayoutExternalRouteRouteImport } from './routes/_layout/external/route'
import { Route as LayoutSynchronizeRouteRouteImport } from './routes/_layout/synchronize/route'
import { Route as LayoutVisualizeRouteRouteImport } from './routes/_layout/visualize/route'
import { Route as LayoutInterrogationsInterrogationIdRouteRouteImport } from './routes/_layout/interrogations/$interrogationId/route'
import { Route as LayoutInterrogationsSynchronizeInterrogationIdRouteRouteImport } from './routes/_layout/interrogations/synchronize/$interrogationId/route'
import { Route as LayoutReviewInterrogationsInterrogationIdRouteRouteImport } from './routes/_layout/review/interrogations/$interrogationId/route'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutEnvRouteRoute = LayoutEnvRouteRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExternalRouteRoute = LayoutExternalRouteRouteImport.update({
  id: '/external',
  path: '/external',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSynchronizeRouteRoute = LayoutSynchronizeRouteRouteImport.update({
  id: '/synchronize',
  path: '/synchronize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVisualizeRouteRoute = LayoutVisualizeRouteRouteImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInterrogationsInterrogationIdRouteRoute =
  LayoutInterrogationsInterrogationIdRouteRouteImport.update({
    id: '/interrogations/$interrogationId',
    path: '/interrogations/$interrogationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInterrogationsSynchronizeInterrogationIdRouteRoute =
  LayoutInterrogationsSynchronizeInterrogationIdRouteRouteImport.update({
    id: '/interrogations/synchronize/$interrogationId',
    path: '/interrogations/synchronize/$interrogationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutReviewInterrogationsInterrogationIdRouteRoute =
  LayoutReviewInterrogationsInterrogationIdRouteRouteImport.update({
    id: '/review/interrogations/$interrogationId',
    path: '/review/interrogations/$interrogationId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteWithChildren
  '/env': typeof LayoutEnvRouteRoute
  '/external': typeof LayoutExternalRouteRoute
  '/synchronize': typeof LayoutSynchronizeRouteRoute
  '/visualize': typeof LayoutVisualizeRouteRoute
  '/interrogations/$interrogationId': typeof LayoutInterrogationsInterrogationIdRouteRoute
  '/interrogations/synchronize/$interrogationId': typeof LayoutInterrogationsSynchronizeInterrogationIdRouteRoute
  '/review/interrogations/$interrogationId': typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteWithChildren
  '/env': typeof LayoutEnvRouteRoute
  '/external': typeof LayoutExternalRouteRoute
  '/synchronize': typeof LayoutSynchronizeRouteRoute
  '/visualize': typeof LayoutVisualizeRouteRoute
  '/interrogations/$interrogationId': typeof LayoutInterrogationsInterrogationIdRouteRoute
  '/interrogations/synchronize/$interrogationId': typeof LayoutInterrogationsSynchronizeInterrogationIdRouteRoute
  '/review/interrogations/$interrogationId': typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/env': typeof LayoutEnvRouteRoute
  '/_layout/external': typeof LayoutExternalRouteRoute
  '/_layout/synchronize': typeof LayoutSynchronizeRouteRoute
  '/_layout/visualize': typeof LayoutVisualizeRouteRoute
  '/_layout/interrogations/$interrogationId': typeof LayoutInterrogationsInterrogationIdRouteRoute
  '/_layout/interrogations/synchronize/$interrogationId': typeof LayoutInterrogationsSynchronizeInterrogationIdRouteRoute
  '/_layout/review/interrogations/$interrogationId': typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/env'
    | '/external'
    | '/synchronize'
    | '/visualize'
    | '/interrogations/$interrogationId'
    | '/interrogations/synchronize/$interrogationId'
    | '/review/interrogations/$interrogationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/env'
    | '/external'
    | '/synchronize'
    | '/visualize'
    | '/interrogations/$interrogationId'
    | '/interrogations/synchronize/$interrogationId'
    | '/review/interrogations/$interrogationId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/env'
    | '/_layout/external'
    | '/_layout/synchronize'
    | '/_layout/visualize'
    | '/_layout/interrogations/$interrogationId'
    | '/_layout/interrogations/synchronize/$interrogationId'
    | '/_layout/review/interrogations/$interrogationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/env': {
      id: '/_layout/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof LayoutEnvRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external': {
      id: '/_layout/external'
      path: '/external'
      fullPath: '/external'
      preLoaderRoute: typeof LayoutExternalRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/synchronize': {
      id: '/_layout/synchronize'
      path: '/synchronize'
      fullPath: '/synchronize'
      preLoaderRoute: typeof LayoutSynchronizeRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/visualize': {
      id: '/_layout/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof LayoutVisualizeRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interrogations/$interrogationId': {
      id: '/_layout/interrogations/$interrogationId'
      path: '/interrogations/$interrogationId'
      fullPath: '/interrogations/$interrogationId'
      preLoaderRoute: typeof LayoutInterrogationsInterrogationIdRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interrogations/synchronize/$interrogationId': {
      id: '/_layout/interrogations/synchronize/$interrogationId'
      path: '/interrogations/synchronize/$interrogationId'
      fullPath: '/interrogations/synchronize/$interrogationId'
      preLoaderRoute: typeof LayoutInterrogationsSynchronizeInterrogationIdRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review/interrogations/$interrogationId': {
      id: '/_layout/review/interrogations/$interrogationId'
      path: '/review/interrogations/$interrogationId'
      fullPath: '/review/interrogations/$interrogationId'
      preLoaderRoute: typeof LayoutReviewInterrogationsInterrogationIdRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutEnvRouteRoute: typeof LayoutEnvRouteRoute
  LayoutExternalRouteRoute: typeof LayoutExternalRouteRoute
  LayoutSynchronizeRouteRoute: typeof LayoutSynchronizeRouteRoute
  LayoutVisualizeRouteRoute: typeof LayoutVisualizeRouteRoute
  LayoutInterrogationsInterrogationIdRouteRoute: typeof LayoutInterrogationsInterrogationIdRouteRoute
  LayoutInterrogationsSynchronizeInterrogationIdRouteRoute: typeof LayoutInterrogationsSynchronizeInterrogationIdRouteRoute
  LayoutReviewInterrogationsInterrogationIdRouteRoute: typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutEnvRouteRoute: LayoutEnvRouteRoute,
  LayoutExternalRouteRoute: LayoutExternalRouteRoute,
  LayoutSynchronizeRouteRoute: LayoutSynchronizeRouteRoute,
  LayoutVisualizeRouteRoute: LayoutVisualizeRouteRoute,
  LayoutInterrogationsInterrogationIdRouteRoute:
    LayoutInterrogationsInterrogationIdRouteRoute,
  LayoutInterrogationsSynchronizeInterrogationIdRouteRoute:
    LayoutInterrogationsSynchronizeInterrogationIdRouteRoute,
  LayoutReviewInterrogationsInterrogationIdRouteRoute:
    LayoutReviewInterrogationsInterrogationIdRouteRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
