/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutVisualizeRouteRouteImport } from './routes/_layout/visualize/route'
import { Route as LayoutSynchronizeRouteRouteImport } from './routes/_layout/synchronize/route'
import { Route as LayoutExternalRouteRouteImport } from './routes/_layout/external/route'
import { Route as LayoutEnvRouteRouteImport } from './routes/_layout/env/route'
import { Route as LayoutInterrogationsInterrogationIdRouteRouteImport } from './routes/_layout/interrogations/$interrogationId/route'
import { Route as LayoutReviewInterrogationsInterrogationIdRouteRouteImport } from './routes/_layout/review/interrogations/$interrogationId/route'
import { Route as LayoutInterrogationsInterrogationIdSynchronizeRouteRouteImport } from './routes/_layout/interrogations/$interrogationId/synchronize/route'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutVisualizeRouteRoute = LayoutVisualizeRouteRouteImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSynchronizeRouteRoute = LayoutSynchronizeRouteRouteImport.update({
  id: '/synchronize',
  path: '/synchronize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExternalRouteRoute = LayoutExternalRouteRouteImport.update({
  id: '/external',
  path: '/external',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvRouteRoute = LayoutEnvRouteRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInterrogationsInterrogationIdRouteRoute =
  LayoutInterrogationsInterrogationIdRouteRouteImport.update({
    id: '/interrogations/$interrogationId',
    path: '/interrogations/$interrogationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutReviewInterrogationsInterrogationIdRouteRoute =
  LayoutReviewInterrogationsInterrogationIdRouteRouteImport.update({
    id: '/review/interrogations/$interrogationId',
    path: '/review/interrogations/$interrogationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInterrogationsInterrogationIdSynchronizeRouteRoute =
  LayoutInterrogationsInterrogationIdSynchronizeRouteRouteImport.update({
    id: '/synchronize',
    path: '/synchronize',
    getParentRoute: () => LayoutInterrogationsInterrogationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteWithChildren
  '/env': typeof LayoutEnvRouteRoute
  '/external': typeof LayoutExternalRouteRoute
  '/synchronize': typeof LayoutSynchronizeRouteRoute
  '/visualize': typeof LayoutVisualizeRouteRoute
  '/interrogations/$interrogationId': typeof LayoutInterrogationsInterrogationIdRouteRouteWithChildren
  '/interrogations/$interrogationId/synchronize': typeof LayoutInterrogationsInterrogationIdSynchronizeRouteRoute
  '/review/interrogations/$interrogationId': typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteWithChildren
  '/env': typeof LayoutEnvRouteRoute
  '/external': typeof LayoutExternalRouteRoute
  '/synchronize': typeof LayoutSynchronizeRouteRoute
  '/visualize': typeof LayoutVisualizeRouteRoute
  '/interrogations/$interrogationId': typeof LayoutInterrogationsInterrogationIdRouteRouteWithChildren
  '/interrogations/$interrogationId/synchronize': typeof LayoutInterrogationsInterrogationIdSynchronizeRouteRoute
  '/review/interrogations/$interrogationId': typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/env': typeof LayoutEnvRouteRoute
  '/_layout/external': typeof LayoutExternalRouteRoute
  '/_layout/synchronize': typeof LayoutSynchronizeRouteRoute
  '/_layout/visualize': typeof LayoutVisualizeRouteRoute
  '/_layout/interrogations/$interrogationId': typeof LayoutInterrogationsInterrogationIdRouteRouteWithChildren
  '/_layout/interrogations/$interrogationId/synchronize': typeof LayoutInterrogationsInterrogationIdSynchronizeRouteRoute
  '/_layout/review/interrogations/$interrogationId': typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/env'
    | '/external'
    | '/synchronize'
    | '/visualize'
    | '/interrogations/$interrogationId'
    | '/interrogations/$interrogationId/synchronize'
    | '/review/interrogations/$interrogationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/env'
    | '/external'
    | '/synchronize'
    | '/visualize'
    | '/interrogations/$interrogationId'
    | '/interrogations/$interrogationId/synchronize'
    | '/review/interrogations/$interrogationId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/env'
    | '/_layout/external'
    | '/_layout/synchronize'
    | '/_layout/visualize'
    | '/_layout/interrogations/$interrogationId'
    | '/_layout/interrogations/$interrogationId/synchronize'
    | '/_layout/review/interrogations/$interrogationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/visualize': {
      id: '/_layout/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof LayoutVisualizeRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/synchronize': {
      id: '/_layout/synchronize'
      path: '/synchronize'
      fullPath: '/synchronize'
      preLoaderRoute: typeof LayoutSynchronizeRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external': {
      id: '/_layout/external'
      path: '/external'
      fullPath: '/external'
      preLoaderRoute: typeof LayoutExternalRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env': {
      id: '/_layout/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof LayoutEnvRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interrogations/$interrogationId': {
      id: '/_layout/interrogations/$interrogationId'
      path: '/interrogations/$interrogationId'
      fullPath: '/interrogations/$interrogationId'
      preLoaderRoute: typeof LayoutInterrogationsInterrogationIdRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review/interrogations/$interrogationId': {
      id: '/_layout/review/interrogations/$interrogationId'
      path: '/review/interrogations/$interrogationId'
      fullPath: '/review/interrogations/$interrogationId'
      preLoaderRoute: typeof LayoutReviewInterrogationsInterrogationIdRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interrogations/$interrogationId/synchronize': {
      id: '/_layout/interrogations/$interrogationId/synchronize'
      path: '/synchronize'
      fullPath: '/interrogations/$interrogationId/synchronize'
      preLoaderRoute: typeof LayoutInterrogationsInterrogationIdSynchronizeRouteRouteImport
      parentRoute: typeof LayoutInterrogationsInterrogationIdRouteRoute
    }
  }
}

interface LayoutInterrogationsInterrogationIdRouteRouteChildren {
  LayoutInterrogationsInterrogationIdSynchronizeRouteRoute: typeof LayoutInterrogationsInterrogationIdSynchronizeRouteRoute
}

const LayoutInterrogationsInterrogationIdRouteRouteChildren: LayoutInterrogationsInterrogationIdRouteRouteChildren =
  {
    LayoutInterrogationsInterrogationIdSynchronizeRouteRoute:
      LayoutInterrogationsInterrogationIdSynchronizeRouteRoute,
  }

const LayoutInterrogationsInterrogationIdRouteRouteWithChildren =
  LayoutInterrogationsInterrogationIdRouteRoute._addFileChildren(
    LayoutInterrogationsInterrogationIdRouteRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutEnvRouteRoute: typeof LayoutEnvRouteRoute
  LayoutExternalRouteRoute: typeof LayoutExternalRouteRoute
  LayoutSynchronizeRouteRoute: typeof LayoutSynchronizeRouteRoute
  LayoutVisualizeRouteRoute: typeof LayoutVisualizeRouteRoute
  LayoutInterrogationsInterrogationIdRouteRoute: typeof LayoutInterrogationsInterrogationIdRouteRouteWithChildren
  LayoutReviewInterrogationsInterrogationIdRouteRoute: typeof LayoutReviewInterrogationsInterrogationIdRouteRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutEnvRouteRoute: LayoutEnvRouteRoute,
  LayoutExternalRouteRoute: LayoutExternalRouteRoute,
  LayoutSynchronizeRouteRoute: LayoutSynchronizeRouteRoute,
  LayoutVisualizeRouteRoute: LayoutVisualizeRouteRoute,
  LayoutInterrogationsInterrogationIdRouteRoute:
    LayoutInterrogationsInterrogationIdRouteRouteWithChildren,
  LayoutReviewInterrogationsInterrogationIdRouteRoute:
    LayoutReviewInterrogationsInterrogationIdRouteRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
