/// <reference types="vite-envs/client" />

type ImportMetaEnv = {
  // Auto-generated by `npx vite-envs update-types` and hot-reloaded by the `vite-env` plugin
  // You probably want to add `/src/vite-env.d.ts` to your .prettierignore
  VITE_QUEEN_API_URL: string
  VITE_EXTERNAL_RESOURCES_URL: string
  VITE_OIDC_ISSUER: string
  VITE_OIDC_CLIENT_ID: string
  VITE_TELEMETRY_ENABLED: string
  VITE_TELEMETRY_MAX_DELAY: string
  VITE_TELEMETRY_MAX_LENGTH: string
  VITE_RESET_MOVED_ENABLED: string
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  APP_VERSION: string
  LUNATIC_VERSION: string
  // @user-defined-start
  /*
   *  You can use this section to explicitly extend the type definition of `import.meta.env`
   *  This is useful if you're using Vite plugins that define specific `import.meta.env` properties.
   *  If you're not using such plugins, this section should remain as is.
   */
  SSR: boolean
  // @user-defined-end
}

interface ImportMeta {
  // Auto-generated by `npx vite-envs update-types`

  url: string

  readonly hot?: import('vite-envs/types/hot').ViteHotContext

  readonly env: ImportMetaEnv

  glob: import('vite-envs/types/importGlob').ImportGlobFunction
}
